### ISSUE TITLE
Hide All but current modal

### ISSUE THREAD

**Issue by mouse0270** [danielpox/better-bootstrap-modals#1]
Would it be possible to add a feature that instead of showing all modals it will hide every modal except the very last one shown, and work its way back words as you close them.

**Comment by mouse0270** [comment]
never mind, I resolved this with a little CSS

``` CSS
.modal-container .modal.in:not(:first-child) {
    display: none!important;
    opacity: 0;
}
```

**Comment by danielpox** [comment]
That is not too bad of an idea. Sometimes, however, it is necessary to be able to view all open modals simultaneously. But, as that is not a very common scenario, I will add the functionality you mentioned as well as add a setting whether to allow multiple open modals.

Thank you for your feedback and for using my framework!

**Comment by mouse0270** [comment]
you could also keep it all in css too. Something like this below, so you can add a `data` option` to make sure the modal is always visible.

``` css
.modal-container .modal.in:not(:first-child) {
    display: none!important;
    opacity: 0;
}
.modal-container .modal.in[data-show-always="true"]:not(:first-child) {
    display: block!important;
    opacity: 1;
}
```
